-- SUBSETS IN SQL:-
--  1)DDL STATEMENTES (DATA DEFINATION LANGUAGE)
-- IN THIS WE HAVE CREATE,ALTER,ADD,DROP,MODIFY,RENAME,TRUNCATE STATEMENTS..
-- THIS DDL STATEMENTS ARE ON AUTO SAVE MODE...

-- CREATE
CREATE TABLE A1 (FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(40),
JOB_ID VARCHAR(60),
SALARY  DECIMAL(9,2),
MANAGER_ID INT UNSIGNED );

-- ALTER AND ADD
ALTER TABLE A1 ADD COLUMN DEPARTMENT_ID INT UNSIGNED;

ALTER TABLE A1 ADD COLUMN HIRED DATE AFTER LAST_NAME;

SELECT * FROM A1;

-- DROP
ALTER TABLE A1 DROP COLUMN HIRED ;

SELECT * FROM A1;

-- MODIFY
ALTER TABLE A1 MODIFY COLUMN SALARY INT UNSIGNED;
DESC A1;

-- RENAME 
ALTER TABLE A1 RENAME COLUMN SALARY TO INCOME;
SELECT * FROM A1;

-- TO DROP A TABLE USE:
DROP TABLE A1;

-- TO TRUNCATE TABLE  USE : THIS WILL DROP ALL THE DATA INSIDE THE TABLE ONLY STRUCTURE WILL REMAIN..
TRUNCATE TABLE A1;

-- TO RENAME TABLE USE
RENAME TABLE A1 TO B1;

RENAME TABLE B1 TO A1;
-- ---------------------------------------------------------------------------------------------------------------------------------------------------




