-- 2) DML (DATA MANUPILATING LANGUAGE).. AND 3) TCL (TRANSACTION CONTROL LANGUAGE)
-- IN DML  WE HAVE INSERT , UPDATE, DELETE....
-- IN TCL WE HAVE COMMIT ,ROLLBACK AND SAVEPOINT..
-- WHEN WE USE DML STATEMENTS A TRANSACTION GET ACTIVE....
-- IN DUMMY ENVIROUNMENT DML STATEMENTS ARE AUTO SAVE MODE BUT IN REAL LIFE DML STATEMENTS ARE NOT ON AUTO SAVE...

SET AUTOCOMMIT=0;

SELECT * FROM A1;

-- INSERT ....
INSERT INTO A1 VALUES ('JOHN','JOSHEP','IT_PROG',30000,103,302);

SELECT * FROM A1;
-- ONLY WE CAN SEE THIS UNTIL WE COMMIT OR ROLLBACK..
ROLLBACK;
SELECT * FROM A1;

INSERT INTO A1 VALUES ('JOHN','JOSHEP','IT_PROG',30000,103,302),
('SAR','FAR','SA_PER', 40000,104,300);
SELECT * FROM A1;


INSERT INTO A1(FIRST_NAME,LAST_NAME,JOB_ID,INCOME,MANAGER_ID) VALUES ('JOHN','JOSHEP','IT_PROG',30000,103),
('SAR','FAR','SA_PER', 40000,104);
SELECT * FROM A1;

INSERT INTO A1(FIRST_NAME,JOB_ID,INCOME,MANAGER_ID) VALUES ('JOHN','IT_PROG',30000,104),
('SAR','SA_PER', 40000,104);
SELECT * FROM A1;

--  TO SAVE WE HAVE TO USE COMMIT..
COMMIT;

-- UPDATE ----
UPDATE  A1
SET INCOME =15000
WHERE MANAGER_ID =104;  -- TO UPDATE ANY WE SHOULD A UNIQUE THING..

SELECT * FROM A1;
ROLLBACK;
SELECT * FROM A1;

UPDATE  A1
SET INCOME =17000
WHERE MANAGER_ID =104;  
SAVEPOINT A;

UPDATE  A1
SET INCOME =19000
WHERE MANAGER_ID =104;  
SAVEPOINT B;

UPDATE  A1
SET FIRST_NAME ='RAZ'
WHERE MANAGER_ID=103;  
SAVEPOINT C;

SELECT * FROM A1;

ROLLBACK TO B; -- THIS WILL ROLLBACK AFTER SAVE POINT B ...
COMMIT; -- TO SAVE UP TO SAVE POINT COMMIT IT...

-- DELETE-- THIS WILL DELETE A ROW..
DELETE FROM A1
WHERE MANAGER_ID=103;

SELECT * FROM A1;
ROLLBACK;

DELETE FROM A1
WHERE DEPARTMENT_ID IN (302,300);

SELECT * FROM A1;

ROLLBACK;

SELECT * FROM A1;