-- CONSTRAINTS / RSETRICTIONS............
-- WE HAVE CONSTRAINTS (NOT NULL,UNIQUE,DEFAULT,CHECK,PRIMARY KEY,FOREIGN KEY)..
-- WHLIE CREATING A TABLE WE WILL GIVE THIS RESTRICTIONS...

-- NOT NULL

CREATE TABLE B1 (EMPLY_ID INT UNSIGNED NOT NULL,
FIRST_NAME VARCHAR(40),
LAST_NAME VARCHAR(50),
SALARY DECIMAL(10,2),
DEPARTMENT_ID INT UNSIGNED);

SELECT * FROM B1;

INSERT INTO B1 VALUES (101,'SAR','FAR',20000,201),
(102,'SAR','FAR',20000,202),
(103,'SAR','FAR',20000,203),
(104,'SAR','FAR',20000,204),
(104,'SAR','FAR',20000,205);

INSERT INTO B1 VALUE (NULL,'SAR','FAR',2990,201); -- THIS WILL SHOW ERROR BCZ EMPLY_ID SHOULD NOT  BE NULL AND DEPARTMENT_ID SHOULD BE UNIQUE..

-- TO DESCRIBE OUR TABLE USE;

DESC B1; -- WHILE INSERTING VALUES EMPLY_ID SHOULD NOT BE NULL..


-- **************************************
-- UNIQUE

ALTER TABLE B1 MODIFY COLUMN DEPARTMENT_ID INT UNSIGNED UNIQUE;


DESC B1; -- WHILE INSERTING VALUES THE DEPARTMENT_ID SHOULD HAVE UNIQUE VALUE..

SELECT * FROM B1;

-- ****************************************************************************************
-- DEFAULT -- IF WE DO NOT INSERT ANY VALUE THE SYS WILL TAKE DEFAULT VALUE...

ALTER TABLE B1 MODIFY COLUMN EMPLY_ID INT UNSIGNED  DEFAULT(40); 
INSERT INTO B1(FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_ID) VALUE ('SAR','FAR',2890,207);
 SELECT * FROM B1;
 
 -- -------------------------------
 -- OTHER CONSTRAINTS ARE TABLE LEVEL CONSTRAINTS..
 -- NOT NULL IS A COLUMN LEVEL CONSTRAINT...

-- ***********************************************************************************************************************************************
-- UNIQUE CONSTRAINT:
 CREATE TABLE C1 (EMPLY_ID INT UNSIGNED  NOT NULL ,
 FIRST_NAME VARCHAR(30),
 LAST_NAME VARCHAR(30),
 SALARY DECIMAL(10,2),
 DEPARTMENT_ID INT UNSIGNED,
 UNIQUE (DEPARTMENT_ID,EMPLY_ID));
 
DESC C1;

-- TO SEE CONSTRAINT NAMES USE:
SELECT COLUMN_NAME,CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME ='C1';

-- TO DROP CONSTRAINT FIRST WE HAVE SEE CONSTRAINT NAME AND DROP...
ALTER TABLE C1 DROP CONSTRAINT DEPARTMENT_ID;

DESC C1;


-- TO ADD CONSTRAINT
ALTER TABLE C1 ADD CONSTRAINT UNI UNIQUE (DEPARTMENT_ID,EMPLY_ID);
DESC C1;
SELECT COLUMN_NAME,CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME ='C1';
-- ------------------
 CREATE TABLE D1 (EMPLY_ID INT UNSIGNED  NOT NULL ,
 FIRST_NAME VARCHAR(30),
 LAST_NAME VARCHAR(30),
 SALARY DECIMAL(10,2),
 DEPARTMENT_ID INT UNSIGNED,
 CONSTRAINT YES UNIQUE (DEPARTMENT_ID,EMPLY_ID));
 
 SELECT COLUMN_NAME,CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME ='D1';
 DESC D1;
 
 ALTER TABLE D1 DROP CONSTRAINT YES ;

-- ******************************************************************************************************************************************
--    PRIMARY KEY----
 -- THE COLUMN WHICH HAVE PRIMARY KEY BY DEFAULT THAT COLUMN WILL HAVE NOT NULL AND UNIQUE CONSTARINT AS WELL..
-- THIS PRIMARY KEY CONSTARINT IS APPLY TO THAT COLUMN WHICH GIVE OVERALL RECORD IDEA..
-- IF WE DO NOT GAVE NAME TO CONSTRAINT IT WILL TAKE COLUMN NAME AS CONSTRAINT NAME..
-- WE CANNOT NAME PRIMARY KEY LIKE WE GAVE NAME TO OTHER CONSTRAINT .. THE DEFAULT NAME OF PRIMARY KEY WILL BE PRIMARY KEY...

CREATE TABLE E1(EMPLY_ID INT UNSIGNED PRIMARY KEY,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(40) DEFAULT('SIR'),
SALARY DECIMAL(7,2) NOT NULL );

DESC E1;

 SELECT COLUMN_NAME,CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME ='D1';


CREATE TABLE F1(EMPLY_ID INT UNSIGNED ,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(40) DEFAULT('SIR'),
SALARY DECIMAL(7,2) ,
PRIMARY KEY (SALARY,EMPLY_ID));

DESC E1;

 SELECT COLUMN_NAME,CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME ='F1';
 
 -- TO DROP 
 ALTER TABLE F1 DROP   PRIMARY KEY ;
 
 SELECT COLUMN_NAME,CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME ='F1';
 
DROP TABLES A1,B1,C1,D1,E1,F1;
 
 
 -- *************************************************************************************************************************
 -- FOREIGN KEY :-
 -- TO JOIN TWO TABLES THERE SHOULD BE RELATIONSHIP BETWEEN THE TABLES.
 -- THE RELATION IS MADE ON THE BASIS OF  FORIEGN KEY CONSTRAINT...
 -- FORIEGN KEY HELPS US TO ESTABLISH RELATIONSHIP BTW TWO TABLES..
 -- TO BUILD A RELATIONSHIP BTW TWO TABLES THERE SHOULD BE ATLEAST ONE SIMILAR COLUMN..
 -- PARENT TABLE IS THAT TABLE WHICH HAVE PRIMARY KEY BESIDE SIMILAR COLUMN..
 -- FOREIGN KEY IS APPLY TO CHILD TABLE..
 
 -- WHEN WE APPLY FOREIGN KEY WE HAVE THREE KEY WORDS FOR SYS TO UNDERSTAND WHERE TO MAKE CHANGES ..
 -- 1)ON DELETE SET NULL:TO DELETE ANY THING FROM PARENT TABLE FIRST CHILD TABLE TO BE INFORM ..SO WHEN WE DELETE A VALUE IN CHILD TABLE  THE SAME VALUE PRESENTE IN PARENT TABLE WILL BECOME NULL ..
 -- 2)ON DELETE CASCADE:TO DELETE ANY THING FROM PARENT TABLE FIRST CHILD TABLE TO BE INFORM ..SO WHEN WE DELETE A VALUE IN CHILD TABLE  
 -- THE ROW IN WHICH SAME VALUE IS PRESENTE IN PARENT TABLE WILL BECOME NULL .. IE COMPLETE ROW WILL BECOME NULL SO MOSTLY WE USE ON DELETE SET NULL..
 -- 3)ON UPDATE CASCADE:TO UPDATE ANY THING TO CHILD TABLE FIRST PARENT TABLE TO BE INFORM ..SO WHEN WE UPDATE A VALUE IN PARENT TABLE  
 -- THE SAME VALUE  PRESENTE IN ANY ROW OF CHILD TABLE WILL CHANGE ..

CREATE TABLE A1(EMPLY_ID INT UNSIGNED NOT NULL,
 FIRST_NAME VARCHAR(40),
 LASTR_NAME VARCHAR(50),
 SALARY DECIMAL(8,2),
 DEPARTMENT_ID INT UNSIGNED PRIMARY KEY);
 
 CREATE TABLE B1(DEPARTMENT_NAMES VARCHAR (30),
 DEPARTMENT_ID INT UNSIGNED,
 FOREIGN KEY (DEPARTMENT_ID) REFERENCES A1(DEPARTMENT_ID) ON DELETE SET NULL  ON UPDATE CASCADE );
 
 -- TO INSERT ANYTHING FIRST PARENT TABLE SHOULD HAVE VALUES..
 INSERT INTO A1 VALUES (101,'SAR','FAR',4000,201),
 (102,'SAR','FAR',4000,202),
 (103,'FAA','KLA',48399,203);
 
 INSERT INTO B1 VALUES('IT',201),
 ('PT',203);
 
 SELECT * FROM A1;
 
 SELECT * FROM B1;
 
 UPDATE A1 
 SET DEPARTMENT_ID =207
 WHERE DEPARTMENT_ID =202;
 
 SELECT * FROM A1;
 
 SELECT * FROM B1;  

DELETE FROM A1
WHERE DEPARTMENT_ID=203;


 SELECT * FROM A1;
 
 SELECT * FROM B1;  -- B1 ALSO GET UPDATED BCZ OF ON DELETE SET NULL..

CREATE TABLE C1(EMPLY_ID INT UNSIGNED NOT NULL,
 FIRST_NAME VARCHAR(40),
 LASTR_NAME VARCHAR(50),
 SALARY DECIMAL(8,2),
 DEPARTMENT_ID INT UNSIGNED PRIMARY KEY);
 
 CREATE TABLE D1(DEPARTMENT_NAMES VARCHAR (30),
 DEPARTMENT_ID INT UNSIGNED,
 CONSTRAINT NEW_1 FOREIGN KEY (DEPARTMENT_ID) REFERENCES A1(DEPARTMENT_ID) ON DELETE SET NULL  ON UPDATE CASCADE );

 SELECT COLUMN_NAME,CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME ='D1';

DESC D1;
-- TO DROP USE;
ALTER TABLE D1 DROP CONSTRAINT NEW_1;

SELECT COLUMN_NAME,CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME ='D1';

-- ****************************************************************************************************************************88888
-- CHECK CONSTRAINT:
-- WE WILL USE THIS CONSTRAINT WHEN WE HAVE A CONDITION WHILE INSERTING VALUES IN COLUMN ..LIKE EX WE HAVE AGE COLUMN AND WE WANT AGE>10 
--  WE WILL  USE CHECK CONSTRAINT IF USER ENTER AGE< 10 

CREATE TABLE F1(EMPLY_ID INT UNSIGNED NOT NULL,
FIRST_NAME VARCHAR(40),
LAST_NAME VARCHAR(30),
AGE INT UNSIGNED CHECK(AGE>10),
SALARY DECIMAL(8,2));

INSERT INTO F1 VALUES(101,'SAR','FAR',5,9000);  -- IT WILL SHOW ERROR BCZ AGE<10..

INSERT INTO F1 VALUES(101,'SAR','FAR',15,9000);

INSERT INTO F1 VALUES(101,'SAR','FAR',-5,9000); -- IT WILL  SHOW ERROR BCZ AGE COLUMN HAS SIGNED VALUE.. 